import { useState } from 'react';
import {
  AlertTriangle,
  AlertCircle,
  CheckCircle2,
  BarChart3,
  ListChecks,
  BookOpen,
  Info,
  Layers,
  Copy,
  Check,
} from 'lucide-react';
import type { PredictionResponse, StudentInput } from '../types/prediction';

type PredictionResultProps = {
  studentInput: StudentInput;
  result: PredictionResponse | null;
  isLoading: boolean;
  errorMessage: string | null;
};

type TabType = 'probabilities' | 'factors' | 'action_plan' | 'resources';

function getRiskMetadata(prediction: PredictionResponse['prediction']) {
  switch (prediction) {
    case 'AT_RISK':
      return {
        label: 'AT RISK - High Priority',
        icon: AlertTriangle,
        tone: 'Student is showing critical warning signs across attendance or practice hours. Immediate mentor intervention is recommended.',
        className: 'AT_RISK',
      };
    case 'NEEDS_ATTENTION':
      return {
        label: 'NEEDS ATTENTION',
        icon: AlertCircle,
        tone: 'Student is meeting baseline criteria but showing minor inconsistencies. Targeted guidance recommended to avoid slippage.',
        className: 'NEEDS_ATTENTION',
      };
    case 'ON_TRACK':
    default:
      return {
        label: 'ON TRACK - Low Risk',
        icon: CheckCircle2,
        tone: 'Student demonstrates strong academic consistency and active practical engagement. Ready for advanced assignments.',
        className: 'ON_TRACK',
      };
  }
}

export function PredictionResult({
  studentInput,
  result,
  isLoading,
  errorMessage,
}: PredictionResultProps) {
  const [activeTab, setActiveTab] = useState<TabType>('probabilities');
  const [copied, setCopied] = useState(false);

  const riskMeta = result ? getRiskMetadata(result.prediction) : null;
  const RiskIcon = riskMeta ? riskMeta.icon : AlertCircle;

  // Copy full summary to clipboard
  const handleCopyReport = () => {
    if (!result) return;
    const reportText = `STUDENT RISK ASSESSMENT REPORT
----------------------------------
Risk Level: ${result.prediction}
Probabilities:
- On Track: ${Math.round(result.probabilities.on_track * 100)}%
- Needs Attention: ${Math.round(result.probabilities.needs_attention * 100)}%
- At Risk: ${Math.round(result.probabilities.at_risk * 100)}%

Metrics Snapshot:
- Attendance: ${studentInput.attendance}%
- Assignments: ${studentInput.assignment_completion}%
- Test Average: ${studentInput.test_average}%
- Coding Hours: ${studentInput.coding_hours} hrs/week
- Projects Completed: ${studentInput.projects_completed}
----------------------------------
Generated by Student Success Predictor`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  // Generate 7-day action items based on input & risk level
  const getActionPlan = () => {
    if (!result) return [];
    if (result.prediction === 'AT_RISK') {
      return [
        { day: 'Day 1', title: 'Mentor 1-on-1 Sync', desc: 'Review attendance gaps and clear pending blockers with learning coach.' },
        { day: 'Day 2', title: 'Catch-up Assignment Blitz', desc: 'Complete overdue core assignment backlogs to boost completion rate.' },
        { day: 'Day 3', title: 'Daily 2-Hour Coding Block', desc: 'Establish a structured 120-min daily coding routine.' },
        { day: 'Day 4', title: 'Fundamental Test Review', desc: 'Re-attempt low-scoring test topics and focus on foundational concepts.' },
        { day: 'Day 5', title: 'Peer Study Group', desc: 'Join guided group sessions for collaborative problem-solving.' },
        { day: 'Day 6', title: 'Project Milestone 1', desc: 'Submit initial blueprint or repository commit for a mini project.' },
        { day: 'Day 7', title: 'Weekly Progress Assessment', desc: 'Review week metrics with mentor to verify track improvement.' },
      ];
    }
    if (result.prediction === 'NEEDS_ATTENTION') {
      return [
        { day: 'Day 1', title: 'Goal Setting Session', desc: 'Define 3 concrete weekly learning goals in the platform dashboard.' },
        { day: 'Day 2', title: 'Assignment Consistency', desc: 'Ensure all current module assignments are submitted 24h before deadline.' },
        { day: 'Day 3-4', title: 'Coding Sprint', desc: 'Target 1.5+ hours of hands-on coding practice each day.' },
        { day: 'Day 5', title: 'Mock Interview Prep', desc: 'Complete 1 hour of mock technical interview practice.' },
        { day: 'Day 6-7', title: 'Mini Project Enhancement', desc: 'Refactor mini-project code and push updates to GitHub.' },
      ];
    }
    return [
      { day: 'Day 1-2', title: 'Advanced Challenge Track', desc: 'Tackle bonus extension problems to push problem-solving limits.' },
      { day: 'Day 3-4', title: 'Full Stack Project Build', desc: 'Build and deploy a capstone project feature with unit tests.' },
      { day: 'Day 5-6', title: 'Peer Mentoring', desc: 'Conduct a code review session for junior cohort students.' },
      { day: 'Day 7', title: 'Career Prep & Resume', desc: 'Update portfolio showcase with recently finished projects.' },
    ];
  };

  // Generate resource suggestions
  const getResources = () => {
    if (!result) return [];
    if (studentInput.attendance < 70 || studentInput.assignment_completion < 70) {
      return [
        { title: 'Time Management & Study Routine', tag: 'Guide', desc: 'Strategies to maintain consistent attendance and schedule coursework.' },
        { title: 'Assignment Catch-Up Bootcamp', tag: 'Video Series', desc: 'Step-by-step walk-throughs of core assignment problems.' },
        { title: 'Foundational Concepts Refresher', tag: 'Docs', desc: 'Key summary cheat sheets for essential programming topics.' },
        { title: 'Mentor Office Hours', tag: 'Live Session', desc: 'Drop-in sessions for real-time guidance and Q&A.' },
      ];
    }
    return [
      { title: 'Data Structures & Algorithms Prep', tag: 'Course', desc: 'Master algorithmic problem solving for technical interviews.' },
      { title: 'Production Ready Project Kit', tag: 'Template', desc: 'Best practices for architecture, CI/CD, and clean code.' },
      { title: 'System Design Basics', tag: 'Article', desc: 'Understanding scalable web services and database modeling.' },
      { title: 'Mock Technical Interview Simulator', tag: 'Interactive', desc: 'Practice live coding interviews under real conditions.' },
    ];
  };

  return (
    <div className="panel" style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <div className="panel-header">
        <div>
          <h2 className="panel-title">
            <BarChart3 size={20} className="gradient-accent-text" />
            AI Risk Analysis & Diagnosis
          </h2>
          <p className="panel-subtitle">Real-time ML prediction probabilities & actionable plan</p>
        </div>

        {result && (
          <button className="btn-secondary" onClick={handleCopyReport} title="Copy Summary Report">
            {copied ? <Check size={14} color="#34d399" /> : <Copy size={14} />}
            <span>{copied ? 'Report Copied!' : 'Export Report'}</span>
          </button>
        )}
      </div>

      {isLoading && (
        <div className="empty-state-box">
          <div className="spinner" style={{ width: 36, height: 36, borderWidth: 3 }} />
          <p>Running ML prediction algorithms...</p>
        </div>
      )}

      {errorMessage && (
        <div className="empty-state-box" style={{ color: '#fca5a5' }}>
          <AlertTriangle size={36} />
          <p>Prediction Error: {errorMessage}</p>
        </div>
      )}

      {!isLoading && !errorMessage && !result && (
        <div className="empty-state-box">
          <div className="empty-state-icon">
            <Layers size={28} />
          </div>
          <h3 style={{ fontSize: '1.1rem', color: 'white' }}>No Active Assessment</h3>
          <p style={{ maxWidth: 360, fontSize: '0.85rem' }}>
            Adjust the student performance metrics on the left or select a quick demo preset above, then click <strong>Run Student Risk Prediction</strong>.
          </p>
        </div>
      )}

      {!isLoading && !errorMessage && result && riskMeta && (
        <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
          {/* Hero Risk Card */}
          <div className={`result-hero-card ${riskMeta.className}`}>
            <div className="result-hero-header">
              <div className={`risk-badge-large ${riskMeta.className}`}>
                <RiskIcon size={22} />
                <span>{riskMeta.label}</span>
              </div>
            </div>

            <p className="risk-subtitle-text">{riskMeta.tone}</p>

            <div className="model-note-box">
              <Info size={16} style={{ flexShrink: 0, color: '#818cf8' }} />
              <span>
                {result.is_temporary
                  ? 'Currently operating on FastAPI rule-based analytics server.'
                  : result.note || 'ML Model Prediction Complete.'}
              </span>
            </div>
          </div>

          {/* Interactive Navigation Tabs */}
          <div className="tabs-header">
            <button
              className={`tab-btn ${activeTab === 'probabilities' ? 'active' : ''}`}
              onClick={() => setActiveTab('probabilities')}
            >
              <BarChart3 size={15} />
              <span>Probabilities</span>
            </button>
            <button
              className={`tab-btn ${activeTab === 'factors' ? 'active' : ''}`}
              onClick={() => setActiveTab('factors')}
            >
              <Layers size={15} />
              <span>Risk Drivers</span>
            </button>
            <button
              className={`tab-btn ${activeTab === 'action_plan' ? 'active' : ''}`}
              onClick={() => setActiveTab('action_plan')}
            >
              <ListChecks size={15} />
              <span>7-Day Action Plan</span>
            </button>
            <button
              className={`tab-btn ${activeTab === 'resources' ? 'active' : ''}`}
              onClick={() => setActiveTab('resources')}
            >
              <BookOpen size={15} />
              <span>Resources</span>
            </button>
          </div>

          {/* Tab 1: Probabilities */}
          {activeTab === 'probabilities' && (
            <div className="probabilities-stack">
              <div className="prob-row">
                <div className="prob-meta">
                  <span>ON TRACK</span>
                  <span style={{ color: '#34d399' }}>
                    {Math.round(result.probabilities.on_track * 100)}%
                  </span>
                </div>
                <div className="prob-track">
                  <div
                    className="prob-fill ON_TRACK"
                    style={{ width: `${result.probabilities.on_track * 100}%` }}
                  />
                </div>
              </div>

              <div className="prob-row">
                <div className="prob-meta">
                  <span>NEEDS ATTENTION</span>
                  <style>{`
                    .color-amber { color: #fbbf24; }
                  `}</style>
                  <span className="color-amber">
                    {Math.round(result.probabilities.needs_attention * 100)}%
                  </span>
                </div>
                <div className="prob-track">
                  <div
                    className="prob-fill NEEDS_ATTENTION"
                    style={{ width: `${result.probabilities.needs_attention * 100}%` }}
                  />
                </div>
              </div>

              <div className="prob-row">
                <div className="prob-meta">
                  <span>AT RISK</span>
                  <span style={{ color: '#f87171' }}>
                    {Math.round(result.probabilities.at_risk * 100)}%
                  </span>
                </div>
                <div className="prob-track">
                  <div
                    className="prob-fill AT_RISK"
                    style={{ width: `${result.probabilities.at_risk * 100}%` }}
                  />
                </div>
              </div>
            </div>
          )}

          {/* Tab 2: Key Risk Drivers */}
          {activeTab === 'factors' && (
            <div className="factors-grid">
              <div
                className={`factor-card ${
                  studentInput.attendance >= 75 ? 'positive' : 'warning'
                }`}
              >
                <div className="factor-title">
                  <span>Attendance: {studentInput.attendance}%</span>
                </div>
                <p className="factor-desc">
                  {studentInput.attendance >= 75
                    ? 'Regular class attendance provides solid foundation.'
                    : 'Low attendance is a primary risk factor impacting overall performance.'}
                </p>
              </div>

              <div
                className={`factor-card ${
                  studentInput.assignment_completion >= 70 ? 'positive' : 'warning'
                }`}
              >
                <div className="factor-title">
                  <span>Assignments: {studentInput.assignment_completion}%</span>
                </div>
                <p className="factor-desc">
                  {studentInput.assignment_completion >= 70
                    ? 'Good homework completion record.'
                    : 'Overdue assignments are accumulating and need immediate focus.'}
                </p>
              </div>

              <div
                className={`factor-card ${
                  studentInput.coding_hours >= 6 ? 'positive' : 'warning'
                }`}
              >
                <div className="factor-title">
                  <span>Coding: {studentInput.coding_hours} hrs/wk</span>
                </div>
                <p className="factor-desc">
                  {studentInput.coding_hours >= 6
                    ? 'Consistent practical hands-on time per week.'
                    : 'Insufficient practice hours to master programming concepts.'}
                </p>
              </div>

              <div
                className={`factor-card ${
                  studentInput.projects_completed >= 2 ? 'positive' : 'warning'
                }`}
              >
                <div className="factor-title">
                  <span>Projects: {studentInput.projects_completed} Completed</span>
                </div>
                <p className="factor-desc">
                  {studentInput.projects_completed >= 2
                    ? 'Active portfolio building progress.'
                    : 'Limited project work completed so far.'}
                </p>
              </div>
            </div>
          )}

          {/* Tab 3: 7-Day Action Plan */}
          {activeTab === 'action_plan' && (
            <div className="action-plan-stack">
              {getActionPlan().map((item, idx) => (
                <div key={idx} className="action-item">
                  <span className="action-day-badge">{item.day}</span>
                  <div className="action-content">
                    <h4>{item.title}</h4>
                    <p>{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Tab 4: Recommended Learning Resources */}
          {activeTab === 'resources' && (
            <div className="resources-grid">
              {getResources().map((res, idx) => (
                <div key={idx} className="resource-card">
                  <div>
                    <span className="resource-tag">{res.tag}</span>
                    <h4 className="resource-title">{res.title}</h4>
                    <p className="factor-desc" style={{ marginTop: '0.35rem' }}>
                      {res.desc}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
