import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  AlertTriangle,
  AlertCircle,
  CheckCircle2,
  BarChart3,
  ListChecks,
  BookOpen,
  Info,
  Layers,
  Copy,
  Check,
  Zap,
  Sparkles,
} from 'lucide-react';
import type { PredictionResponse, StudentInput } from '../types/prediction';

type PredictionResultProps = {
  studentInput: StudentInput;
  result: PredictionResponse | null;
  isLoading: boolean;
  errorMessage: string | null;
};

type TabType = 'llm_advice' | 'probabilities' | 'factors' | 'action_plan' | 'resources';


function getRiskMetadata(prediction: PredictionResponse['prediction']) {
  switch (prediction) {
    case 'AT_RISK':
      return {
        label: 'AT RISK - High Priority',
        icon: AlertTriangle,
        tone: 'Student is showing critical warning signs across attendance or practice hours. Immediate mentor intervention is recommended.',
        bannerBg: 'from-rose-950/80 via-slate-950 to-slate-950 border-rose-500/50 shadow-rose-500/20 text-rose-400',
        badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
      };
    case 'NEEDS_ATTENTION':
      return {
        label: 'NEEDS ATTENTION',
        icon: AlertCircle,
        tone: 'Student is meeting baseline criteria but showing minor inconsistencies. Targeted guidance recommended to avoid slippage.',
        bannerBg: 'from-amber-950/80 via-slate-950 to-slate-950 border-amber-500/50 shadow-amber-500/20 text-amber-400',
        badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      };
    case 'ON_TRACK':
    default:
      return {
        label: 'ON TRACK - Low Risk',
        icon: CheckCircle2,
        tone: 'Student demonstrates strong academic consistency and active practical engagement. Ready for advanced assignments.',
        bannerBg: 'from-emerald-950/80 via-slate-950 to-slate-950 border-emerald-500/50 shadow-emerald-500/20 text-emerald-400',
        badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      };
  }
}

export function PredictionResult({
  studentInput,
  result,
  isLoading,
  errorMessage,
}: PredictionResultProps) {
  const [activeTab, setActiveTab] = useState<TabType>('llm_advice');

  const [copied, setCopied] = useState(false);

  const riskMeta = result ? getRiskMetadata(result.prediction) : null;
  const RiskIcon = riskMeta ? riskMeta.icon : AlertCircle;

  // Copy full summary to clipboard
  const handleCopyReport = () => {
    if (!result) return;
    const reportText = `STUDENT RISK ASSESSMENT REPORT
----------------------------------
Risk Level: ${result.prediction}
Probabilities:
- On Track: ${Math.round(result.probabilities.on_track * 100)}%
- Needs Attention: ${Math.round(result.probabilities.needs_attention * 100)}%
- At Risk: ${Math.round(result.probabilities.at_risk * 100)}%

Metrics Snapshot:
- Attendance: ${studentInput.attendance}%
- Assignments: ${studentInput.assignment_completion}%
- Test Average: ${studentInput.test_average}%
- Coding Hours: ${studentInput.coding_hours} hrs/week
- Projects Completed: ${studentInput.projects_completed}
----------------------------------
Generated by Student Success Predictor`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  // Generate 7-day action items based on input & risk level
  const getActionPlan = () => {
    if (!result) return [];
    if (result.prediction === 'AT_RISK') {
      return [
        { day: 'Day 1', title: 'Mentor 1-on-1 Sync', desc: 'Review attendance gaps and clear pending blockers with learning coach.' },
        { day: 'Day 2', title: 'Catch-up Assignment Blitz', desc: 'Complete overdue core assignment backlogs to boost completion rate.' },
        { day: 'Day 3', title: 'Daily 2-Hour Coding Block', desc: 'Establish a structured 120-min daily coding routine.' },
        { day: 'Day 4', title: 'Fundamental Test Review', desc: 'Re-attempt low-scoring test topics and focus on foundational concepts.' },
        { day: 'Day 5', title: 'Peer Study Group', desc: 'Join guided group sessions for collaborative problem-solving.' },
        { day: 'Day 6', title: 'Project Milestone 1', desc: 'Submit initial blueprint or repository commit for a mini project.' },
        { day: 'Day 7', title: 'Weekly Progress Assessment', desc: 'Review week metrics with mentor to verify track improvement.' },
      ];
    }
    if (result.prediction === 'NEEDS_ATTENTION') {
      return [
        { day: 'Day 1', title: 'Goal Setting Session', desc: 'Define 3 concrete weekly learning goals in the platform dashboard.' },
        { day: 'Day 2', title: 'Assignment Consistency', desc: 'Ensure all current module assignments are submitted 24h before deadline.' },
        { day: 'Day 3-4', title: 'Coding Sprint', desc: 'Target 1.5+ hours of hands-on coding practice each day.' },
        { day: 'Day 5', title: 'Mock Interview Prep', desc: 'Complete 1 hour of mock technical interview practice.' },
        { day: 'Day 6-7', title: 'Mini Project Enhancement', desc: 'Refactor mini-project code and push updates to GitHub.' },
      ];
    }
    return [
      { day: 'Day 1-2', title: 'Advanced Challenge Track', desc: 'Tackle bonus extension problems to push problem-solving limits.' },
      { day: 'Day 3-4', title: 'Full Stack Project Build', desc: 'Build and deploy a capstone project feature with unit tests.' },
      { day: 'Day 5-6', title: 'Peer Mentoring', desc: 'Conduct a code review session for junior cohort students.' },
      { day: 'Day 7', title: 'Career Prep & Resume', desc: 'Update portfolio showcase with recently finished projects.' },
    ];
  };

  // Generate resource suggestions
  const getResources = () => {
    if (!result) return [];
    if (studentInput.attendance < 70 || studentInput.assignment_completion < 70) {
      return [
        { title: 'Time Management & Study Routine', tag: 'Guide', desc: 'Strategies to maintain consistent attendance and schedule coursework.' },
        { title: 'Assignment Catch-Up Bootcamp', tag: 'Video Series', desc: 'Step-by-step walk-throughs of core assignment problems.' },
        { title: 'Foundational Concepts Refresher', tag: 'Docs', desc: 'Key summary cheat sheets for essential programming topics.' },
        { title: 'Mentor Office Hours', tag: 'Live Session', desc: 'Drop-in sessions for real-time guidance and Q&A.' },
      ];
    }
    return [
      { title: 'Data Structures & Algorithms Prep', tag: 'Course', desc: 'Master algorithmic problem solving for technical interviews.' },
      { title: 'Production Ready Project Kit', tag: 'Template', desc: 'Best practices for architecture, CI/CD, and clean code.' },
      { title: 'System Design Basics', tag: 'Article', desc: 'Understanding scalable web services and database modeling.' },
      { title: 'Mock Technical Interview Simulator', tag: 'Interactive', desc: 'Practice live coding interviews under real conditions.' },
    ];
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45, delay: 0.1 }}
      className="p-6 rounded-3xl bg-slate-950/80 backdrop-blur-xl border border-slate-800/80 shadow-2xl flex flex-col justify-between h-full"
    >
      <div className="flex items-center justify-between pb-4 border-b border-slate-800/80 mb-5">
        <div>
          <h2 className="text-lg font-black text-white flex items-center gap-2">
            <BarChart3 size={20} className="text-indigo-400" />
            AI Risk Analysis & Diagnosis
          </h2>
          <p className="text-xs text-slate-400">Real-time ML prediction probabilities & actionable plan</p>
        </div>

        {result && (
          <motion.button 
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-800 bg-slate-900 text-slate-300 hover:text-white hover:bg-slate-800 text-xs font-semibold shadow-sm transition-all" 
            onClick={handleCopyReport} 
            title="Copy Summary Report"
          >
            {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
            <span>{copied ? 'Report Copied!' : 'Export Report'}</span>
          </motion.button>
        )}
      </div>

      {isLoading && (
        <div className="flex flex-col items-center justify-center py-16 gap-3 text-slate-400 text-sm">
          <div className="w-10 h-10 rounded-full border-3 border-indigo-500 border-t-transparent animate-spin" />
          <p className="font-semibold text-slate-300 animate-pulse">Evaluating student risk parameters...</p>
        </div>
      )}

      {errorMessage && (
        <div className="flex flex-col items-center justify-center py-16 gap-3 text-rose-400 text-sm">
          <AlertTriangle size={40} />
          <p className="font-semibold">Prediction Error: {errorMessage}</p>
        </div>
      )}

      {!isLoading && !errorMessage && !result && (
        <div className="flex flex-col items-center justify-center py-16 gap-3 text-center">
          <div className="w-14 h-14 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex items-center justify-center mb-1">
            <Layers size={30} />
          </div>
          <h3 className="text-base font-extrabold text-white">No Active Assessment</h3>
          <p className="text-xs text-slate-400 max-w-xs">
            Adjust the student metrics on the left or select a quick demo preset above, then click <strong>Run Student Risk Prediction</strong>.
          </p>
        </div>
      )}

      {!isLoading && !errorMessage && result && riskMeta && (
        <div className="flex flex-col flex-1 gap-5">
          {/* Hero Risk Banner Card */}
          <motion.div 
            initial={{ scale: 0.98, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ duration: 0.35 }}
            className={`p-5 rounded-2xl bg-gradient-to-br border shadow-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${riskMeta.bannerBg}`}
          >
            <div className="flex flex-col gap-2.5 flex-1">
              <div className="flex items-center justify-between">
                <span className={`inline-flex items-center gap-2 px-3.5 py-1 rounded-full text-xs font-black uppercase tracking-wider border ${riskMeta.badgeBg}`}>
                  <RiskIcon size={16} />
                  <span>{riskMeta.label}</span>
                </span>
                <Sparkles size={16} className="text-indigo-400 sm:hidden" />
              </div>

              <p className="text-xs text-slate-200 leading-relaxed">{riskMeta.tone}</p>

              <div className="flex items-center gap-2 text-[11px] text-slate-400 bg-slate-950/80 p-2.5 rounded-xl border border-slate-800">
                <Info size={14} className="text-indigo-400 flex-shrink-0" />
                <span>
                  {result.is_temporary
                    ? 'Calculated via real-time analytical evaluation engine.'
                    : result.note || 'ML Model Prediction Complete.'}
                </span>
              </div>
            </div>

            {/* AI Model Confidence Gauge */}
            <div className="flex flex-col items-center justify-center p-3 rounded-2xl bg-slate-950/80 border border-slate-800 min-w-[130px] flex-shrink-0 text-center">
              <div className="relative w-16 h-16 flex items-center justify-center">
                <svg className="w-full h-full transform -rotate-90" viewBox="0 0 60 60">
                  <circle
                    cx="30"
                    cy="30"
                    r="25"
                    stroke="currentColor"
                    strokeWidth="5"
                    className="text-slate-800"
                    fill="transparent"
                  />
                  <motion.circle
                    cx="30"
                    cy="30"
                    r="25"
                    stroke="currentColor"
                    strokeWidth="5"
                    strokeDasharray={157}
                    initial={{ strokeDashoffset: 157 }}
                    animate={{ strokeDashoffset: 157 - (157 * Math.max(result.probabilities.on_track, result.probabilities.needs_attention, result.probabilities.at_risk)) }}
                    transition={{ duration: 1, ease: 'easeOut' }}
                    strokeLinecap="round"
                    className={
                      result.prediction === 'ON_TRACK'
                        ? 'text-emerald-400'
                        : result.prediction === 'AT_RISK'
                        ? 'text-rose-400'
                        : 'text-amber-400'
                    }
                    fill="transparent"
                  />
                </svg>
                <span className="absolute text-xs font-black text-white font-mono">
                  {Math.round(Math.max(result.probabilities.on_track, result.probabilities.needs_attention, result.probabilities.at_risk) * 100)}%
                </span>
              </div>
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400 mt-1">
                Model Confidence
              </span>
            </div>
          </motion.div>

          {/* Interactive Navigation Tabs */}
          <div className="flex items-center p-1 bg-slate-900/90 rounded-xl border border-slate-800 gap-1 text-xs overflow-x-auto scrollbar-none">
            {[
              { id: 'llm_advice', label: 'AI Coach (LLM)', icon: Sparkles },
              { id: 'probabilities', label: 'Probabilities', icon: BarChart3 },
              { id: 'factors', label: 'Risk Drivers', icon: Layers },
              { id: 'action_plan', label: '7-Day Plan', icon: ListChecks },
              { id: 'resources', label: 'Resources', icon: BookOpen },
            ].map((tab) => {
              const TabIcon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as TabType)}
                  className={`relative flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg font-bold transition-all whitespace-nowrap z-10 ${
                    isActive ? 'text-white' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {isActive && (
                    <motion.div
                      layoutId="activeTabPill"
                      className="absolute inset-0 bg-indigo-600 rounded-lg -z-10 shadow-md shadow-indigo-500/20"
                      transition={{ type: 'spring', stiffness: 400, damping: 30 }}
                    />
                  )}
                  <TabIcon size={14} />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>

          <AnimatePresence mode="wait">
            {/* Tab 0: AI Coach (LLM) Advice */}
            {activeTab === 'llm_advice' && (
              <motion.div
                key="llm"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex flex-col gap-3 p-4 rounded-2xl bg-slate-900/80 border border-slate-800/80 max-h-64 overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-slate-800 text-xs"
              >
                <div className="flex items-center justify-between gap-2 pb-2 border-b border-slate-800/80">
                  <span className="flex items-center gap-1.5 font-black text-indigo-300">
                    <Sparkles size={14} className="text-amber-400 animate-pulse" />
                    <span>Personalized AI Coaching Letter</span>
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full bg-indigo-500/15 text-indigo-300 border border-indigo-500/30 text-[10px] font-mono font-bold">
                    {result.rag_recommendations?.llm_provider || 'Vector RAG + LLM Engine'}
                  </span>
                </div>

                {result.rag_recommendations?.llm_summary && (
                  <div className="p-3 rounded-xl bg-indigo-950/40 border border-indigo-500/30 text-indigo-200 leading-relaxed font-medium">
                    <span className="font-bold text-white block mb-0.5">Executive Diagnosis:</span>
                    {result.rag_recommendations.llm_summary}
                  </div>
                )}

                <div className="text-slate-300 leading-relaxed whitespace-pre-wrap font-sans">
                  {result.rag_recommendations?.llm_coaching_advice || (
                    <p className="text-slate-400 italic">Run risk prediction to generate synthesized LLM recommendations.</p>
                  )}
                </div>
              </motion.div>
            )}

            {/* Tab 1: Probabilities */}
            {activeTab === 'probabilities' && (
              <motion.div 

                key="prob"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex flex-col gap-4 p-4 rounded-2xl bg-slate-900/60 border border-slate-800/80"
              >
                {[
                  { label: 'ON TRACK', val: result.probabilities.on_track, color: 'text-emerald-400', barBg: 'bg-emerald-500' },
                  { label: 'NEEDS ATTENTION', val: result.probabilities.needs_attention, color: 'text-amber-400', barBg: 'bg-amber-500' },
                  { label: 'AT RISK', val: result.probabilities.at_risk, color: 'text-rose-400', barBg: 'bg-rose-500' },
                ].map((item) => (
                  <div key={item.label} className="flex flex-col gap-1.5">
                    <div className="flex justify-between text-xs font-mono font-bold">
                      <span className="text-slate-300">{item.label}</span>
                      <span className={item.color}>{Math.round(item.val * 100)}%</span>
                    </div>
                    <div className="w-full bg-slate-950 h-2 rounded-full overflow-hidden border border-slate-800">
                      <motion.div 
                        initial={{ width: 0 }}
                        animate={{ width: `${item.val * 100}%` }}
                        transition={{ duration: 0.6, ease: 'easeOut' }}
                        className={`h-full rounded-full ${item.barBg}`}
                      />
                    </div>
                  </div>
                ))}
              </motion.div>
            )}

            {/* Tab 2: Key Risk Drivers */}
            {activeTab === 'factors' && (
              <motion.div 
                key="factors"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="grid grid-cols-1 sm:grid-cols-2 gap-3"
              >
                {[
                  {
                    title: `Attendance: ${studentInput.attendance}%`,
                    isGood: studentInput.attendance >= 75,
                    desc: studentInput.attendance >= 75 ? 'Regular attendance provides solid foundation.' : 'Low attendance is a primary risk factor.',
                  },
                  {
                    title: `Assignments: ${studentInput.assignment_completion}%`,
                    isGood: studentInput.assignment_completion >= 70,
                    desc: studentInput.assignment_completion >= 70 ? 'Good homework completion record.' : 'Overdue assignments accumulating.',
                  },
                  {
                    title: `Coding: ${studentInput.coding_hours} hrs/wk`,
                    isGood: studentInput.coding_hours >= 6,
                    desc: studentInput.coding_hours >= 6 ? 'Consistent practical hands-on time.' : 'Insufficient practice hours.',
                  },
                  {
                    title: `Projects: ${studentInput.projects_completed} Built`,
                    isGood: studentInput.projects_completed >= 2,
                    desc: studentInput.projects_completed >= 2 ? 'Active portfolio building.' : 'Limited project work so far.',
                  },
                ].map((factor, i) => (
                  <div
                    key={i}
                    className={`p-3.5 rounded-xl border text-xs flex flex-col gap-1 ${
                      factor.isGood
                        ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-300'
                        : 'bg-rose-500/10 border-rose-500/20 text-rose-300'
                    }`}
                  >
                    <span className="font-bold">{factor.title}</span>
                    <span className="text-[11px] text-slate-300">{factor.desc}</span>
                  </div>
                ))}
              </motion.div>
            )}

            {/* Tab 3: 7-Day Action Plan */}
            {activeTab === 'action_plan' && (
              <motion.div 
                key="action"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex flex-col gap-2.5 max-h-64 overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-slate-800"
              >
                {getActionPlan().map((item, idx) => (
                  <div key={idx} className="p-3 rounded-xl bg-slate-900/70 border border-slate-800 flex items-start gap-3 text-xs">
                    <span className="px-2 py-0.5 rounded-md bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 font-mono font-extrabold flex-shrink-0">
                      {item.day}
                    </span>
                    <div>
                      <h4 className="font-bold text-white">{item.title}</h4>
                      <p className="text-[11px] text-slate-400 mt-0.5">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </motion.div>
            )}

            {/* Tab 4: Recommended Learning Resources */}
            {activeTab === 'resources' && (
              <motion.div 
                key="res"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="grid grid-cols-1 sm:grid-cols-2 gap-3"
              >
                {getResources().map((res, idx) => (
                  <div key={idx} className="p-3.5 rounded-xl bg-slate-900/70 border border-slate-800 flex flex-col justify-between gap-1 text-xs">
                    <div>
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-cyan-500/15 text-cyan-300 border border-cyan-500/30">
                        {res.tag}
                      </span>
                      <h4 className="font-bold text-white mt-1.5">{res.title}</h4>
                      <p className="text-[11px] text-slate-400 mt-1">{res.desc}</p>
                    </div>
                  </div>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}
    </motion.div>
  );
}

