import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  AlertTriangle,
  AlertCircle,
  CheckCircle2,
  BarChart3,
  ListChecks,
  BookOpen,
  Info,
  Layers,
  Copy,
  Check,
  Sparkles,
  ExternalLink,
  Cpu,
  FileText,
} from 'lucide-react';
import type { PredictionResponse, StudentInput } from '../types/prediction';
import { useAppDispatch, useAppSelector } from '../store';
import { setActiveTab } from '../store/predictionSlice';
import { useUI } from '../context/UIContext';

type PredictionResultProps = {
  studentInput?: StudentInput;
  result?: PredictionResponse | null;
  isLoading?: boolean;
  errorMessage?: string | null;
};

type TabType = 'llm_advice' | 'probabilities' | 'factors' | 'action_plan' | 'resources';

function getRiskMetadata(prediction: PredictionResponse['prediction']) {
  switch (prediction) {
    case 'AT_RISK':
      return {
        label: 'AT RISK - High Priority',
        icon: AlertTriangle,
        tone: 'Student is showing critical warning signs across attendance or practice hours. Immediate mentor intervention is recommended.',
        bannerBg: 'from-rose-950/80 via-slate-950 to-slate-950 border-rose-500/40 text-rose-300',
        badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
      };
    case 'NEEDS_ATTENTION':
      return {
        label: 'NEEDS ATTENTION',
        icon: AlertCircle,
        tone: 'Student is meeting baseline criteria but showing minor inconsistencies. Targeted guidance recommended to avoid slippage.',
        bannerBg: 'from-amber-950/80 via-slate-950 to-slate-950 border-amber-500/40 text-amber-300',
        badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      };
    case 'ON_TRACK':
    default:
      return {
        label: 'ON TRACK - Low Risk',
        icon: CheckCircle2,
        tone: 'Student demonstrates strong academic consistency and active practical engagement. Ready for advanced assignments.',
        bannerBg: 'from-emerald-950/80 via-slate-950 to-slate-950 border-emerald-500/40 text-emerald-300',
        badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      };
  }
}

export function PredictionResult({
  studentInput: propInput,
  result: propResult,
  isLoading: propLoading,
  errorMessage: propError,
}: PredictionResultProps) {
  const dispatch = useAppDispatch();
  const { showToast } = useUI();

  const reduxInput = useAppSelector((state) => state.prediction.input);
  const reduxResult = useAppSelector((state) => state.prediction.result);
  const reduxStatus = useAppSelector((state) => state.prediction.status);
  const reduxError = useAppSelector((state) => state.prediction.error);
  const reduxActiveTab = useAppSelector((state) => state.prediction.activeTab);

  const [localActiveTab, setLocalActiveTab] = useState<TabType>('llm_advice');
  const [copied, setCopied] = useState(false);

  const studentInput = propInput || reduxInput;
  const result = propResult !== undefined ? propResult : reduxResult;
  const isLoading = propLoading !== undefined ? propLoading : reduxStatus === 'loading';
  const errorMessage = propError !== undefined ? propError : reduxError;
  const activeTab = (reduxActiveTab as TabType) || localActiveTab;

  const handleTabChange = (tab: TabType) => {
    setLocalActiveTab(tab);
    dispatch(setActiveTab(tab));
  };

  const riskMeta = result ? getRiskMetadata(result.prediction) : null;
  const RiskIcon = riskMeta ? riskMeta.icon : AlertCircle;

  const rag = result?.rag_recommendations;

  // Copy full summary report to clipboard
  const handleCopyReport = () => {
    if (!result || !studentInput) return;
    const reportText = `STUDENT SUCCESS DIAGNOSTIC REPORT
==================================
Risk Classification: ${result.prediction}
Confidence: ${Math.round((result.probabilities[result.prediction.toLowerCase() as keyof typeof result.probabilities] || 0) * 100)}%

Student Inputs:
- Attendance: ${studentInput.attendance}%
- Assignment Completion: ${studentInput.assignment_completion}%
- Test Average: ${studentInput.test_average}%
- Coding Hours: ${studentInput.coding_hours} hrs/week
- Projects Completed: ${studentInput.projects_completed}

RAG Vector Retrieval Status: Active (${rag?.retrieved_documents.length || 0} Docs Matches)
----------------------------------
Generated by Student Success Predictor`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    showToast('Diagnostic report copied to clipboard!', 'success');
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45, delay: 0.1 }}
      className="p-6 rounded-3xl bg-slate-950/80 backdrop-blur-xl border border-slate-800/80 shadow-2xl flex flex-col h-full"
    >
      <div className="flex items-center justify-between pb-4 border-b border-slate-800/80 mb-5">
        <div>
          <h2 className="text-lg font-black text-white flex items-center gap-2">
            <BarChart3 size={20} className="text-indigo-400" />
            AI Risk Analysis & RAG Interventions
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">Real-time ML prediction probabilities & vector-retrieved recommendations</p>
        </div>

        {result && (
          <motion.button 
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.96 }}
            className="flex items-center gap-2 px-3 py-1.5 rounded-xl border border-slate-800 bg-slate-900/80 text-slate-300 hover:text-white hover:border-indigo-500/40 text-xs font-semibold shadow-md transition-all cursor-pointer"
            onClick={handleCopyReport}
            title="Copy Summary Report"
          >
            {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
            <span>{copied ? 'Report Copied!' : 'Export Report'}</span>
          </motion.button>
        )}
      </div>

      {isLoading && (
        <div className="flex flex-col items-center justify-center py-16 gap-3 text-slate-400 text-sm">
          <div className="w-10 h-10 rounded-full border-3 border-indigo-500 border-t-transparent animate-spin" />
          <p className="font-semibold text-slate-300 animate-pulse">Evaluating student risk parameters...</p>
        </div>
      )}

      {errorMessage && (
        <div className="flex flex-col items-center justify-center py-16 gap-3 text-rose-400 text-sm">
          <AlertTriangle size={40} />
          <p className="font-semibold">Prediction Error: {errorMessage}</p>
        </div>
      )}


      {!isLoading && !errorMessage && !result && (
        <div className="flex flex-col items-center justify-center py-16 gap-3 text-center flex-1">
          <div className="w-14 h-14 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex items-center justify-center mb-1">
            <Layers size={30} />
          </div>
          <h3 className="text-base font-extrabold text-white">No Active Assessment</h3>
          <p className="text-xs text-slate-400 max-w-xs">
            Adjust the student metrics on the left or select a quick demo preset above, then click <strong>Run Student Risk Prediction</strong>.
          </p>
        </div>
      )}

      {!isLoading && !errorMessage && result && riskMeta && (
        <div className="flex flex-col flex-1 gap-5">
          {/* Hero Risk Banner Card */}
          <motion.div 
            initial={{ scale: 0.98, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ duration: 0.35 }}
            className={`p-5 rounded-2xl bg-gradient-to-br border shadow-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${riskMeta.bannerBg}`}
          >
            <div className="flex flex-col gap-2.5 flex-1">
              <div className="flex items-center justify-between">
                <span className={`inline-flex items-center gap-2 px-3.5 py-1 rounded-full text-xs font-black uppercase tracking-wider border ${riskMeta.badgeBg}`}>
                  <RiskIcon size={16} />
                  <span>{riskMeta.label}</span>
                </span>
                <Sparkles size={16} className="text-indigo-400 sm:hidden" />
              </div>

              <p className="text-xs text-slate-200 leading-relaxed">{riskMeta.tone}</p>

              <div className="flex items-center gap-2 text-[11px] text-slate-400 bg-slate-950/80 p-2.5 rounded-xl border border-slate-800 flex-wrap">
                <Info size={14} className="text-indigo-400 flex-shrink-0" />
                <span>{result.note}</span>
                <span className="ml-auto text-[10px] px-2 py-0.5 rounded-md bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 font-mono font-bold flex items-center gap-1">
                  <Cpu size={10} /> RAG Enabled
                </span>
              </div>
            </div>

            {/* AI Model Confidence Gauge */}
            <div className="flex flex-col items-center justify-center p-3 rounded-2xl bg-slate-950/80 border border-slate-800 min-w-[130px] flex-shrink-0 text-center">
              <div className="relative w-16 h-16 flex items-center justify-center">
                <svg className="w-full h-full transform -rotate-90" viewBox="0 0 60 60">
                  <circle
                    cx="30"
                    cy="30"
                    r="25"
                    stroke="currentColor"
                    strokeWidth="5"
                    className="text-slate-800"
                    fill="transparent"
                  />
                  <motion.circle
                    cx="30"
                    cy="30"
                    r="25"
                    stroke="currentColor"
                    strokeWidth="5"
                    strokeDasharray={157}
                    initial={{ strokeDashoffset: 157 }}
                    animate={{ strokeDashoffset: 157 - (157 * Math.max(result.probabilities.on_track, result.probabilities.needs_attention, result.probabilities.at_risk)) }}
                    transition={{ duration: 1, ease: 'easeOut' }}
                    strokeLinecap="round"
                    className={
                      result.prediction === 'ON_TRACK'
                        ? 'text-emerald-400'
                        : result.prediction === 'AT_RISK'
                        ? 'text-rose-400'
                        : 'text-amber-400'
                    }
                    fill="transparent"
                  />
                </svg>
                <span className="absolute text-xs font-black text-white font-mono">
                  {Math.round(Math.max(result.probabilities.on_track, result.probabilities.needs_attention, result.probabilities.at_risk) * 100)}%
                </span>
              </div>
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400 mt-1">
                Model Certainty
              </span>
            </div>
          </motion.div>

          {/* Interactive Navigation Tabs */}
          <div className="flex items-center p-1 bg-slate-900/90 rounded-xl border border-slate-800 gap-1 text-xs overflow-x-auto scrollbar-none">
            {[
              { id: 'llm_advice', label: 'AI Coach (LLM)', icon: Sparkles },
              { id: 'probabilities', label: 'Probabilities', icon: BarChart3 },
              { id: 'factors', label: 'RAG Drivers & Docs', icon: Layers },
              { id: 'action_plan', label: 'RAG 7-Day Plan', icon: ListChecks },
              { id: 'resources', label: 'Retrieved Resources', icon: BookOpen },
            ].map((tab) => {
              const TabIcon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => handleTabChange(tab.id as TabType)}

                  className={`relative flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg font-bold transition-all whitespace-nowrap z-10 ${
                    isActive ? 'text-white' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {isActive && (
                    <motion.div
                      layoutId="activeTabPill"
                      className="absolute inset-0 bg-indigo-600 rounded-lg -z-10 shadow-md shadow-indigo-500/20"
                      transition={{ type: 'spring', stiffness: 400, damping: 30 }}
                    />
                  )}
                  <TabIcon size={14} />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>

          <AnimatePresence mode="wait">
            {/* Tab 0: AI Coach (LLM) Advice */}
            {activeTab === 'llm_advice' && (
              <motion.div
                key="llm"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex flex-col gap-3 p-4 rounded-2xl bg-slate-900/80 border border-slate-800/80 max-h-64 overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-slate-800 text-xs"
              >
                <div className="flex items-center justify-between gap-2 pb-2 border-b border-slate-800/80">
                  <span className="flex items-center gap-1.5 font-black text-indigo-300">
                    <Sparkles size={14} className="text-amber-400 animate-pulse" />
                    <span>Personalized AI Coaching Letter</span>
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full bg-indigo-500/15 text-indigo-300 border border-indigo-500/30 text-[10px] font-mono font-bold">
                    {result.rag_recommendations?.llm_provider || 'Vector RAG + LLM Engine'}
                  </span>
                </div>

                {result.rag_recommendations?.llm_summary && (
                  <div className="p-3 rounded-xl bg-indigo-950/40 border border-indigo-500/30 text-indigo-200 leading-relaxed font-medium">
                    <span className="font-bold text-white block mb-0.5">Executive Diagnosis:</span>
                    {result.rag_recommendations.llm_summary}
                  </div>
                )}

                <div className="text-slate-300 leading-relaxed whitespace-pre-wrap font-sans">
                  {result.rag_recommendations?.llm_coaching_advice || (
                    <p className="text-slate-400 italic">Run risk prediction to generate synthesized LLM recommendations.</p>
                  )}
                </div>
              </motion.div>
            )}

            {/* Tab 1: Probabilities */}
            {activeTab === 'probabilities' && (
              <motion.div 

                key="prob"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex flex-col gap-4 p-4 rounded-2xl bg-slate-900/60 border border-slate-800/80"
              >
                {[
                  { key: 'on_track', label: 'ON TRACK', prob: result.probabilities.on_track, color: 'emerald', barBg: 'bg-emerald-500', text: 'text-emerald-400' },
                  { key: 'needs_attention', label: 'NEEDS ATTENTION', prob: result.probabilities.needs_attention, color: 'amber', barBg: 'bg-amber-500', text: 'text-amber-400' },
                  { key: 'at_risk', label: 'AT RISK', prob: result.probabilities.at_risk, color: 'rose', barBg: 'bg-rose-500', text: 'text-rose-400' },
                ].map((item) => (
                  <div key={item.key} className="flex flex-col gap-1.5">
                    <div className="flex items-center justify-between text-xs font-bold">
                      <span className="text-slate-300">{item.label}</span>
                      <span className={`font-mono text-sm ${item.text}`}>{Math.round(item.prob * 100)}%</span>
                    </div>
                    <div className="w-full bg-slate-950 h-2 rounded-full overflow-hidden border border-slate-800">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${item.prob * 100}%` }}
                        transition={{ duration: 0.8, ease: 'easeOut' }}
                        className={`h-full rounded-full ${item.barBg}`}
                      />
                    </div>
                  </div>
                ))}
              </motion.div>
            )}

            {/* Tab 2: RAG Risk Drivers & Retrieved Documents */}
            {activeTab === 'factors' && (
              <motion.div 
                key="factors"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex flex-col gap-3"
              >
                {/* Identified Risk Drivers */}
                <div className="p-3.5 rounded-2xl bg-slate-900/70 border border-slate-800">
                  <span className="text-[11px] font-extrabold uppercase tracking-wider text-indigo-400 block mb-2">
                    Identified Metric Deficits
                  </span>
                  <div className="flex flex-wrap gap-2">
                    {rag?.risk_drivers.map((driver, idx) => (
                      <span key={idx} className="text-xs px-2.5 py-1 rounded-lg bg-indigo-500/10 border border-indigo-500/30 text-indigo-300 font-semibold">
                        • {driver}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Retrieved RAG Knowledge Documents */}
                <div className="flex flex-col gap-2.5">
                  <span className="text-[11px] font-extrabold uppercase tracking-wider text-slate-400 block">
                    Retrieved Knowledge Base Modules ({rag?.retrieved_documents.length || 0} Matches)
                  </span>
                  {rag?.retrieved_documents.map((doc) => (
                    <div key={doc.id} className="p-3.5 rounded-2xl bg-slate-900/40 border border-slate-800/80 flex flex-col gap-1.5">
                      <div className="flex items-center justify-between gap-2">
                        <span className="font-bold text-xs text-white flex items-center gap-1.5">
                          <FileText size={14} className="text-indigo-400" />
                          {doc.title}
                        </span>
                        <span className="text-[10px] font-mono px-2 py-0.5 rounded-md bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 font-bold">
                          {Math.round(doc.relevance_score * 100)}% Vector Match
                        </span>
                      </div>
                      <p className="text-xs text-slate-400 leading-relaxed">{doc.description}</p>
                    </div>
                  ))}
                </div>
              </motion.div>
            )}

            {/* Tab 3: RAG 7-Day Action Plan */}
            {activeTab === 'action_plan' && (
              <motion.div 
                key="plan"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex flex-col gap-2.5 max-h-[320px] overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-slate-800"
              >
                {rag?.action_plan.map((item, idx) => (
                  <motion.div 
                    key={item.day}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.25, delay: idx * 0.05 }}
                    whileHover={{ x: 3, scale: 1.01 }}
                    className="flex items-start gap-3 p-3 rounded-2xl bg-slate-900/60 border border-slate-800/80 text-left transition-colors hover:bg-slate-900/90"
                  >
                    <span className="text-xs font-mono font-extrabold px-2.5 py-1 rounded-xl bg-indigo-600 text-white flex-shrink-0 shadow-sm">
                      Day {item.day}
                    </span>
                    <div className="flex flex-col">
                      <span className="text-xs font-bold text-slate-200 leading-snug">{item.task}</span>
                    </div>
                  </motion.div>
                ))}
              </motion.div>
            )}

            {/* Tab 4: RAG Retrieved Learning Resources */}
            {activeTab === 'resources' && (
              <motion.div 
                key="resources"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-h-[320px] overflow-y-auto pr-1"
              >
                {rag?.resources.map((res, idx) => (
                  <motion.a
                    key={idx}
                    href={res.url}
                    target="_blank"
                    rel="noreferrer"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.25, delay: idx * 0.05 }}
                    whileHover={{ y: -2, scale: 1.02 }}
                    className="p-3.5 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-indigo-500/50 hover:bg-slate-900 transition-all flex flex-col justify-between gap-2 group text-left"
                  >
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-[10px] font-mono uppercase font-bold px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-300 border border-indigo-500/20">
                          {res.type}
                        </span>
                        <ExternalLink size={13} className="text-slate-500 group-hover:text-indigo-400 transition-colors" />
                      </div>
                      <span className="text-xs font-bold text-white block group-hover:text-indigo-300 transition-colors">
                        {res.name}
                      </span>
                    </div>
                    {res.source_doc && (
                      <span className="text-[10px] text-slate-500 truncate">
                        Source: {res.source_doc}
                      </span>
                    )}
                  </motion.a>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}
    </motion.div>
  );
}

